# Generated by Django 3.0.6 on 2020-05-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200515_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ticari', 'Ticari'), ('Otomasyon', 'Otomasyon'), ('Muhasebe', 'Muhasebe')], max_length=200, null=True),
        ),
    ]
