# Generated by Django 3.0.6 on 2020-05-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='person',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
