# Generated by Django 3.0.6 on 2020-05-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200516_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('delivered', 'Teslim Edildi')], max_length=200, null=True),
        ),
    ]
