# Generated by Django 3.0.6 on 2020-05-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
