# Generated by Django 3.0.6 on 2020-05-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200516_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pruduct_key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
