# Generated by Django 3.0.6 on 2020-05-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_customer_bakim_anlasmasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bakim_baslangic',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bakim_bitis',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
