# Generated by Django 3.0.6 on 2020-05-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200518_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bakim_anlasmasi',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bakim_baslangic',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bakim_bitis',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pruduct_key',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tax_number',
        ),
    ]
