# Generated by Django 3.0.6 on 2020-05-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200518_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_durumu',
            field=models.CharField(choices=[('Gönderildi', 'Gönderildi'), ('Gönderilmedi', 'Gönderilmedi')], max_length=200, null=True),
        ),
    ]
