# Generated by Django 3.0.6 on 2020-06-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_customer_email_durumu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='alternative_solution',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date_created',
        ),
        migrations.AddField(
            model_name='service',
            name='service_date',
            field=models.DateTimeField(null=True),
        ),
    ]
