# Generated by Django 3.0.6 on 2020-07-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_date',
            field=models.DateTimeField(null=True),
        ),
    ]
