# Generated by Django 3.0.6 on 2020-07-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_todo_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Tamamlandı', 'Tamamlandı')], max_length=200, null=True),
        ),
    ]
