# Generated by Django 3.0.6 on 2020-07-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_contactformmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmessage',
            name='userName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
