# Generated by Django 3.0.6 on 2020-07-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20200729_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmessage',
            name='userName',
        ),
        migrations.AddField(
            model_name='contactformmessage',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
    ]
