# Generated by Django 3.0.6 on 2020-07-29 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20200729_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmessage',
            name='customer',
        ),
        migrations.AddField(
            model_name='contactformmessage',
            name='userName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
