# Generated by Django 3.0.6 on 2020-07-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20200729_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='userName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
