# Generated by Django 3.0.6 on 2020-07-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20200729_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='subject',
            field=models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Closed', 'Closed')], max_length=50),
        ),
    ]
