# Generated by Django 3.0.6 on 2020-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20200729_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='subject',
            field=models.CharField(choices=[('Teknik Destek Talebi', 'Teknik Destek Talebi'), ('Lisans Talebi', 'Lisans Talebi'), ('Ürün Güncelleştirme', 'Ürün Güncelleştirme'), ('Yeni Satın Alım Talebi', 'Yeni Satın Alım Talebi'), ('Memnuniyetsizlik', 'Memnuniyetsizlik'), ('Tavsiye', 'Tavsiye'), ('Diğer', 'Diğer')], max_length=50),
        ),
    ]
