# Generated by Django 3.0.6 on 2020-07-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_ticket_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(choices=[('Servis 1', 'Servis 1'), ('Servis 2', 'Servis 2')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='solution_name',
            field=models.CharField(choices=[('Çözüm 1_1', 'Çözüm 1_1'), ('Çözüm 1_2', 'Çözüm 1_2'), ('Çözüm 2_1', 'Çözüm 2_1'), ('Çözüm 2_2', 'Çözüm 2_2')], max_length=1000, null=True),
        ),
    ]
