# Generated by Django 3.0.6 on 2020-07-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20200730_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.AutoField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
