# Generated by Django 3.0.6 on 2020-07-30 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0057_service_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bakim_anlasmasi',
            field=models.CharField(blank=True, choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bakim_baslangic',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bakim_bitis',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_durumu',
            field=models.CharField(blank=True, choices=[('Gönderildi', 'Gönderildi'), ('Gönderilmedi', 'Gönderilmedi')], max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='userName',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
