# Generated by Django 3.0.6 on 2020-08-04 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0058_auto_20200730_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_admin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bakim_anlasmasi',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bakim_baslangic',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bakim_bitis',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_durumu',
            field=models.CharField(choices=[('Gönderildi', 'Gönderildi'), ('Gönderilmedi', 'Gönderilmedi')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='userName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
