# Generated by Django 3.0.6 on 2020-08-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_auto_20200804_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'get_latest_by': 'id'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Closed', 'Closed')], default='New', max_length=10),
        ),
    ]
