# Generated by Django 3.0.6 on 2020-08-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20200811_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rate',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
