# Generated by Django 3.0.6 on 2020-08-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_ticket_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='rate',
            field=models.IntegerField(blank=True, choices=[('Çok Kötü', 'Çok Kötü'), ('Kötü', 'Kötü'), ('Orta', 'Orta'), ('İyi', 'İyi'), ('Çok İyi', 'Çok İyi'), ('Tavsiye', 'Tavsiye'), ('Mükemmel', 'Mükemmel')]),
        ),
    ]
