# Generated by Django 3.0.6 on 2020-08-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20200812_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketService',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Service'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='maintenance',
            field=models.CharField(blank=True, choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], max_length=200, null=True),
        ),
    ]
