# Generated by Django 3.0.6 on 2020-08-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20200812_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticketService',
        ),
    ]
