# Generated by Django 3.0.6 on 2020-08-12 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0068_remove_ticket_ticketservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userName',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
