# Generated by Django 3.0.6 on 2020-08-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_auto_20200812_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ticketNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
