# Generated by Django 3.0.6 on 2020-08-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_customer_ticketnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ticketNumber',
        ),
        migrations.AddField(
            model_name='service',
            name='ticketNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
