# Generated by Django 3.0.6 on 2020-08-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_auto_20200813_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('explanation', models.CharField(blank=True, max_length=100, null=True)),
                ('productKey', models.CharField(blank=True, max_length=100, null=True)),
                ('returnNo', models.CharField(blank=True, max_length=100, null=True)),
                ('control1', models.CharField(blank=True, max_length=100, null=True)),
                ('control2', models.CharField(blank=True, max_length=100, null=True)),
                ('control3', models.CharField(blank=True, max_length=100, null=True)),
                ('control4', models.CharField(blank=True, max_length=100, null=True)),
                ('control5', models.CharField(blank=True, max_length=100, null=True)),
                ('portNo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
