# Generated by Django 3.0.6 on 2020-09-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_auto_20200902_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='message',
            new_name='comment',
        ),
    ]
